---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy
  labels:
    app: facebook

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: facebook
    
  template:
    metadata:
      name: facebook-pod
      labels:
        app: facebook
        version: V1_AC
    spec:
      containers:
        - name: facebook-pod-cont
          image: devopshubg333/batch13:mindcircuit13img
          ports:
            - containerPort: 8080
