---
apiVersion: v1
kind: Service
metadata:
  name: fb-np-svc
  labels:
    app: facebook

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31333
      protocol: TCP
  selector:
    app: facebook